name: Release Workflow
on:
  release:
    types: [created]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Install Goreleaser
        run: |
             GO111MODULE=on go get github.com/goreleaser/goreleaser@v0.179.1
              export PATH="${PATH}:${HOME}/go/bin"


      - name: Build and Release
        run: |
            go mod tidy
             export PATH="${PATH}:${HOME}/go/bin"
              go get github.com/goreleaser/goreleaser@v0.179.1
               goreleaser release --rm-dist

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USER }}/SuperCalculator:1.1.1 .

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USER }}/SuperCalculator:1.1.1
