name: Release Workflow

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      checks: write
      contents: write
      deployments: write
      id-token: write
      issues: write
      pull-requests: write
      repository-projects: write
      security-events: write
      statuses: write
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: stable

    - name: Build and Release
      uses: goreleaser/goreleaser-action@v4
      if: success() && startsWith(github.ref, 'refs/tags/')
      with: 
        version: latest 
        args: release --clean
      env:
        GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx 
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build And Publish Image 
      uses: docker/build-push-action@v4
      with: 
        context: . 
        file: Dockerfile 
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/4dvp_docker:${{ github.ref_name }}
